=== wplatform/db-incubator/neradb-engine/src/main/resources/META-INF/ddal-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--

        Copyright 2014-2015 the original author or authors

        Licensed under the Apache License, Version 2.0 (the “License”);
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

             http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an “AS IS” BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

        -->
        <!ELEMENT ddal-config (settings?,schema,cluster,dataNodes?,algorithms?)>

        <!ELEMENT settings (property*)>

        <!ELEMENT schema (tableGroup*, table*, sequence*)>
        <!ATTLIST schema
                name CDATA #REQUIRED
                public CDATA #IMPLIED
                force (true|false) #IMPLIED
                >


        <!ELEMENT cluster (shard+)>
        <!ELEMENT shard (member+)>
        <!ATTLIST shard
                name CDATA #REQUIRED
                >


        <!ELEMENT dataNodes (datasource+)>
        <!ELEMENT datasource (property*)>
        <!ATTLIST datasource
                id CDATA #REQUIRED
                class CDATA #IMPLIED
                jndi-name CDATA #IMPLIED
                >

        <!ELEMENT algorithms (ruleAlgorithm+)>
        <!ELEMENT ruleAlgorithm (property*)>
        <!ATTLIST ruleAlgorithm
                name CDATA #REQUIRED
                class CDATA #REQUIRED
                > 

        <!ELEMENT table ((nodes|node|broadcast)?, tableRule?)>
        <!ATTLIST table
                name CDATA #REQUIRED
                ruleColumns CDATA #IMPLIED
                metaNodeIndex CDATA #IMPLIED
                scanLevel (unlimited|anyIndex|uniqueIndex|shardingKey) #IMPLIED
                >

        <!ELEMENT tableGroup (tables, nodes, tableRule)>
        <!ATTLIST tableGroup
                metaNodeIndex CDATA #IMPLIED
                scanLevel (unlimited|anyIndex|uniqueIndex|shardingKey) #IMPLIED
                >
        <!ELEMENT tables (table+)>
                
        <!ELEMENT sequence (property*)>
        <!ATTLIST sequence
                name CDATA #REQUIRED
                strategy (hilo|seqhilo|snowflake) #REQUIRED
                >

        <!ELEMENT property (#PCDATA)>
        <!ATTLIST property
                name CDATA #REQUIRED
                value CDATA #REQUIRED
                >


        <!ELEMENT member (#PCDATA)>
        <!ATTLIST member
                ref CDATA #REQUIRED
                wWeight CDATA #IMPLIED
                rWeight CDATA #IMPLIED
                > 

        <!ELEMENT nodes (node+)>
        <!ELEMENT broadcast (#PCDATA|node)*>
        <!ELEMENT tableRule (columns,algorithm)>

        <!ELEMENT node (#PCDATA)>
        <!ATTLIST node
                shard CDATA #REQUIRED
                catalog CDATA #IMPLIED
                schema CDATA #IMPLIED
                name CDATA #IMPLIED
                suffix CDATA #IMPLIED
                >
                
        <!ELEMENT columns (#PCDATA)>
        <!ELEMENT algorithm (#PCDATA)>

=== wplatform/db-incubator/openddal-tests/src/test/resources/conf/JoinFree.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ddal-config PUBLIC "-//openddal.com//DTD ddal-config//EN" "http://openddal.com/dtd/ddal-config.dtd">
<ddal-config>

	<settings>
		<property name="sqlMode" value="MySQL" />
		<property name="transactionMode" value="BESTEFFORTS_1PC" />
		<property name="defaultQueryTimeout" value="3000000" />
		<property name="validationQuery" value="select 1" />
		<property name="validationQueryTimeout" value="1000" />
	</settings>

	<schema name="JOINFREE_TEST" force="false">

		<tableGroup>
			<tables>
				<table name="g1_table1" ruleColumns="id" />
				<table name="g1_table2" ruleColumns="ref_id" />
			</tables>
			<nodes>
				<node shard="shard0" suffix="_01,_02" />
				<node shard="shard1" suffix="_01,_02" />
				<node shard="shard2" suffix="_01,_02" />
				<node shard="shard3" suffix="_01,_02" />
			</nodes>
			<tableRule>
				<columns>${table.ruleColumns}</columns>
				<algorithm>customer_partitioner</algorithm>
			</tableRule>
		</tableGroup>

		<tableGroup>
			<tables>
				<table name="g2_table1" ruleColumns="id, main_id" />
				<table name="g2_table2" ruleColumns="ref_id, main_id" />
				<table name="g2_table3" ruleColumns="ref_id, main_id" />
			</tables>
			<nodes>
				<node shard="shard0" suffix="_01,_02" />
				<node shard="shard1" suffix="_01,_02" />
				<node shard="shard2" suffix="_01,_02" />
				<node shard="shard3" suffix="_01,_02" />
			</nodes>
			<tableRule>
				<columns>${table.ruleColumns}</columns>
				<algorithm>MultColumnPartitioner</algorithm>
			</tableRule>
		</tableGroup>

		<table name="global1">
			<broadcast>shard0,shard1,shard2,shard3</broadcast>
		</table>

		<table name="global2">
			<broadcast>shard0,shard1,shard2,shard3</broadcast>
		</table>

		<sequence name="joinfree_test_seq" strategy="hilo">
			<property name="shard" value="shard0" />
			<property name="cacheSize" value="1" />
		</sequence>
		<sequence name="joinfree_seq2" strategy="hilo">
			<property name="shard" value="shard0" />
			<property name="cacheSize" value="1" />
		</sequence>
		<sequence name="joinfree_seq3" strategy="hilo">
			<property name="shard" value="shard0" />
			<property name="cacheSize" value="1" />
		</sequence>
	</schema>

	<cluster>
		<shard name="shard0">
			<member ref="db1m" />
		</shard>
		<shard name="shard1">
			<member ref="db2m" />
		</shard>
		<shard name="shard2">
			<member ref="db3m" />
		</shard>
		<shard name="shard3">
			<member ref="db4m" />
		</shard>
	</cluster>


	<dataNodes>
		<datasource id="db1m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url"
				value="jdbc:mysql://10.199.188.136:3306/ddal_db1?connectTimeout=1000&amp;rewriteBatchedStatements=true" />
			<property name="username" value="root" />
			<property name="password" value="!Passw0rd01" />
			<property name="maxWait" value="0" />
			<property name="poolPreparedStatements" value="true" />
		</datasource>
		<datasource id="db2m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url"
				value="jdbc:mysql://10.199.188.136:3306/ddal_db2?connectTimeout=1000&amp;rewriteBatchedStatements=true" />
			<property name="username" value="root" />
			<property name="password" value="!Passw0rd01" />
			<property name="maxWait" value="0" />
			<property name="poolPreparedStatements" value="true" />
		</datasource>
		<datasource id="db3m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url"
				value="jdbc:mysql://10.199.188.136:3306/ddal_db3?connectTimeout=1000&amp;rewriteBatchedStatements=true" />
			<property name="username" value="root" />
			<property name="password" value="!Passw0rd01" />
			<property name="maxWait" value="0" />
			<property name="poolPreparedStatements" value="true" />
		</datasource>
		<datasource id="db4m" class="org.apache.commons.dbcp.BasicDataSource">
			<property name="driverClassName" value="com.mysql.jdbc.Driver" />
			<property name="url"
				value="jdbc:mysql://10.199.188.136:3306/ddal_db4?connectTimeout=1000&amp;rewriteBatchedStatements=true" />
			<property name="username" value="root" />
			<property name="password" value="!Passw0rd01" />
			<property name="maxWait" value="0" />
			<property name="poolPreparedStatements" value="true" />
		</datasource>
	</dataNodes>


	<algorithms>
		<ruleAlgorithm name="customer_partitioner"
			class="com.openddal.route.algorithm.HashBucketPartitioner">
			<property name="partitionCount" value="8" />
			<property name="partitionLength" value="128" />
		</ruleAlgorithm>
		<ruleAlgorithm name="order_partitioner"
			class="com.openddal.route.algorithm.HashBucketPartitioner">
			<property name="partitionCount" value="16" />
			<property name="partitionLength" value="64" />
		</ruleAlgorithm>
		<ruleAlgorithm name="MultColumnPartitioner"
			class="com.openddal.test.utils.MultColumnPartitioner">
			<property name="dbCount" value="4" />
			<property name="tblCount" value="2" />
		</ruleAlgorithm>
	</algorithms>

</ddal-config>
